In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set(style = 'darkgrid')

In [4]:
df = pd.read_csv('forecasting_case_study.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product             1218 non-null   object
 1   date                1218 non-null   object
 2   Sales               1218 non-null   int64
 3   Price Discount (%)  1218 non-null   object
 4   In-Store Promo      1218 non-null   int64
 5   Catalogue Promo     1218 non-null   int64
 6   Store End Promo     1218 non-null   int64
 7   Google_Mobility     1218 non-null   float64
 8   Covid_Flag          1218 non-null   int64
 9   V_DAY               1218 non-null   int64
 10  EASTER              1218 non-null   int64
 11  CHRISTMAS           1218 non-null   int64
dtypes: float64(1), int64(8), object(3)
memory usage: 114.3+ KB

## For Null Variables

In [6]:
df.isnull().sum()

Product               0
date                  0
Sales                 0
Price Discount (%)    0
In-Store Promo        0
Catalogue Promo       0
Store End Promo       0
Google_Mobility       0
Covid_Flag            0
V_DAY                 0
EASTER                0
CHRISTMAS             0
dtype: int64

In [7]:
df.fillna(method = 'bfill')
#filling the null with backward data

,Product,date,Sales,Price Discount (%),In-Store Promo,Catalogue Promo,Store End Promo,Google_Mobility,Covid_Flag,V_DAY,EASTER,CHRISTMAS
0,SKU1,2/5/2017,27750,0%,0,0,0,0.00,0,0,0,0
1,SKU1,2/12/2017,29023,0%,1,0,1,0.00,0,1,0,0
2,SKU1,2/19/2017,45630,17%,0,0,0,0.00,0,0,0,0
3,SKU1,2/26/2017,26789,0%,1,0,1,0.00,0,0,0,0
4,SKU1,3/5/2017,41999,17%,0,0,0,0.00,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1213,SKU6,10/18/2020,96619,54%,0,1,0,-7.56,1,0,0,0
1214,SKU6,10/25/2020,115798,52%,0,1,0,-8.39,1,0,0,0
1215,SKU6,11/1/2020,152186,54%,1,0,1,-7.43,1,0,0,0
1216,SKU6,11/8/2020,26445,44%,1,0,1,-5.95,1,0,0,0
1217,SKU6,11/15/2020,26414,44%,0,0,0,-7.20,1,0,0,0

In [9]:
df.null.interpolate()
#filling nulls with average of the value before and after

AttributeError: 'DataFrame' object has no attribute 'null'

## Outliers

In [13]:
import sklearn 
from sklearn.preprocessing import RobustScaler
df = pd.read_csv('forecasting_case_study.csv')
scaler = RobustScaler()
df = scaler.fit_transform(data)

ValueError: could not convert string to float: 'SKU1'

## Duplicates

In [12]:
df= df.drop_duplicates()